package com.Loop.Erands.Models;

public enum Category {
    ELECTRONICS,WME,
    MOBILE_PHONES, MOBILE_ACCESSORIES,
    COMPUTER, COMPUTER_ACCESSORIES, LAPTOPS, DESKTOPS, PC,

    HOME,
    HOME_APPLIANCES,HOME_DECOR,FURNITURE,
    AUTOMOBILE,
    AUTOMOBILE_ACCESSORIES, CAR, BIKE, CYCLE,

    GROCERY,
    VEGETABLE,PULSES, CEREALS,

    DRESS,
    CLOTHING,TOP_WEAR, BOTTOM_WEAR,
    MEN,WOMEN,SHIRT,PANT,JEAN,T_SHIRT,SHORTS,INNER_WEAR,VEST,BRIEF,
    SHOES,SLIPPERS,FLIP_FLOP,
    SPECTACLES ,WATCH ,

    SPORT_WEAR,PART_WEAR, PARTY_WEAR, CASUAL_WEAR
}
