package com.Loop.Erands.Models;

public enum Colour {
    RED, GREEN, BLUE, YELLOW, ORANGE, PURPLE, PINK, BROWN, BLACK, WHITE,
    GRAY, CYAN, MAGENTA, TEAL, MAROON, NAVY, OLIVE, LIME, GOLD, SILVER,
    BRONZE, INDIGO, VIOLET, TURQUOISE, CORAL,MIXED
}
